/* test.jj        example from JavaCC tutorial */
options {
    STATIC = false;    
}

PARSER_BEGIN(Adder)

//package com.anjuke.corp.mysqlparser;

    class Adder{
        public static void main(String [] args)
        throws ParseException , TokenMgrError {
            Adder parser = new Adder( System.in );
            parser.Start();
        }
    }

PARSER_END(Adder)

SKIP : {" "}
SKIP : {"\n" | "\r" | "\r\n" }
TOKEN : {< PLUS : "+" >}
TOKEN : {< NUMBER : (["0"-"9"])+ >}

int Start() throws NumberFormatException:{
    Token t;
    int i;
    int value;
}{
    t = <NUMBER>
    { i = Integer.parseInt(t.image);}
    { value = i;}
    (
        <PLUS>
        t = <NUMBER>
        {i = Integer.parseInt(t.image);}
        {value += i;}
    )*
    <EOF>
    {System.out.print(value);}
    {return value;}
}
