/* Generated By:JavaCC: Do not edit this line. Eg4TreeConstants.java Version 5.0 */
public interface Eg4TreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTMULT = 3;
  public int JJTMYOTHERID = 4;
  public int JJTINTEGER = 5;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Add",
    "Mult",
    "MyOtherID",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=a43aa4b9c6e7ace8fd3d78299732080e (do not edit this line) */
