/* Generated By:JavaCC: Do not edit this line. Eg4Visitor.java Version 5.0 */
public interface Eg4Visitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTMult node, Object data);
  public Object visit(ASTMyOtherID node, Object data);
  public Object visit(ASTInteger node, Object data);
}
/* JavaCC - OriginalChecksum=61e5f2fcdf1507c6289c7ec44d382157 (do not edit this line) */
